### ISSUE TITLE
Enable prefix for gcc-like compiler

### ISSUE THREAD

**Issue by gwilga** [maven-nar/nar-maven-plugin#191]
Feature: Add a custom compiler that is based on gcc.

Usually, a custom compiler has a prefix (example: arm-bistro-linux-gnueabi-gcc).
Currently, I did not found a way to use it easily without any code change. 

I tried with usage of aol.properties, but failed on nar-validate or nar-compile...

I have currently found 2 possibilities to use it:
 - Add a new compiler into the CppTask. 
Not a really good solution, because if we want to add a new compiler, we need to re-add it into CppTask...

 - Use the 'gcc-cross' class, already available in CppTack, with a new tag for the pom (prefix), and the usage of aol.properties.
Can be a good candidate.

**Comment by markjohndoyle** [comment]
I added a change (https://github.com/maven-nar/nar-maven-plugin/commit/e6e70ce67ebd4209dece2aee1d3927081472532f) to support ccache which is a wrapper but works like a prefix. 

You may find some ideas from that commit. I had the idea that it would be expanded from a specific ccache option to a prefix/wrapper/decorator option. Currently it replaces the compiler binary/exe (e.g. gcc) with ccache and pushes the compiler exe into the command args

So:
`gcc blah blah blah`

becomes

`ccache gcc blah blah blah`

The big difference in your issue is that there is a space in the ccache prefix concept therefore the command array is manipulated. I think the concepts might be similar enough though.

The config could be:
`<wrapper>ccache</wrapper>`
`<prefix>arm-bistro-linux-gnueabi-</prefix>`

**Comment by gwilga** [comment]
I already have something that works fine.

With my small modification, the pom.xml config could be:
```
<configuration>
    <aol>arm-Linux-gpp</aol>
    <linker>
        <name>gcc-cross</name>
        <prefix>arm-linux-gnueabi</prefix>
        <toolPath>/usr/bin</toolPath>
    </linker>
    <cpp>
        <name>gcc-cross</name>
        <prefix>arm-linux-gnueabi</prefix>
        <toolPath>/usr/bin</toolPath>
    </cpp>
    <c>
        <name>gcc-cross</name>
        <prefix>arm-linux-gnueabi</prefix>
        <toolPath>/usr/bin</toolPath>
    </c>
</configuration>
```
And the aol.properties:
```
arm.Linux.gpp.cpp.compiler=g++
arm.Linux.gpp.cpp.prefix=arm-linux-gnueabi
arm.Linux.gpp.cpp.defines=ARM LINUX
arm.Linux.gpp.cpp.options=-c -fPIC -pthread -fexceptions -O2 -fno-strict-aliasing -fno-omit-frame-pointer -Wall -Wextra
arm.Linux.gpp.cpp.includes=**/*.cc **/*.cpp **/*.cxx
arm.Linux.gpp.cpp.excludes=

arm.Linux.gpp.c.compiler=gcc
arm.Linux.gpp.c.prefix=arm-linux-gnueabi
arm.Linux.gpp.c.defines=ARM LINUX
arm.Linux.gpp.c.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion -fPIC
arm.Linux.gpp.c.includes=**/*.c
arm.Linux.gpp.c.excludes=

# options for gcc linker front end
arm.Linux.gpp.linker.options=-shared -shared-libgcc -fPIC -fexceptions
arm.Linux.gpp.linker.sysLibs=
arm.Linux.gpp.linker.libs=

arm.Linux.gpp.java.include=include;include/linux
arm.Linux.gpp.java.runtimeDirectory=jre/lib/i386/client

arm.Linux.gpp.lib.prefix=lib
arm.Linux.gpp.shared.prefix=lib
arm.Linux.gpp.static.extension=a
arm.Linux.gpp.shared.extension=so
arm.Linux.gpp.plugin.extension=so
arm.Linux.gpp.jni.extension=so
arm.Linux.gpp.executable.extension=
```

Which use /usr/bin/arm-linux-gnueabi-gcc for linker and compiler, to generate the arm-Linux-gcc aol.

This example, is more a cross-compilation example.

**Comment by gwilga** [comment]
Finally, I change the implementation regarding your remarks.

I have just added the prefix option, in the same ways as the ccache option. I have not added the gcc-cross, g++-cross linker.

**Comment by gwilga** [comment]
Modification can be seen with #197 pull request.

**Comment by ctrueden** [comment]
#197 was merged! It would still be great to get a regression test for it, though.
