### ISSUE TITLE
Unable to generate shared library from parent project with 8 threads

### ISSUE THREAD

**Issue by duckladydinh** [maven-nar/nar-maven-plugin#346]
Hallo,

i have a big maven project and a small module called native which uses maven-nar-plugin. When I do something like mvn clean install -T 8, the nar-compile failed since it could not find some dependent files. But if I do use 4 threads or less, or do clean install directly in the native folder, it would be perfectly fine.

Does anyone experience the same issue? I would appreciate if you can give me a hint.

Thank you.

**Comment by GregDomjan** [comment]
We build a project of about 150 modules, but only single-threaded due to issues like this.

The related problems seem to be
 * identifying the plugin as safe/unsafe for threaded usage
 * incomplete support of listing dependencies to the maven resolver - only the metadata jar is added
 * only tracking packed/installed artifacts - requiring install and subsequent unpack of dependency to properly refer to it

In theory, Maven can schedule a compile if all other dependencies have passed compile stage, but at that point, the artifact references in the reactor don't list the AOL dependencies. Also when they get added during download step when not already added in the reactor, they aren't looking for unpacked source dirs, only the .nar to unpack.
