### ISSUE TITLE
MSVC x86 architecture builds on x64 host do not compile.

### ISSUE THREAD

**Issue by vindiagram** [maven-nar/nar-maven-plugin#369]
For MSVC versions 14.0 and older when compiling on a x64 host machine and targeting an x86 architecture the nar-maven-plugin will use the amd64_x86 cross compiler folder under the bin directory. 

Without using the vcvarsall script to properly configure environment variables all calls to these cross compilers will fail.
The only other way to compile x86 is to use the default VC\bin directory which is the default x86 compiler on windows and VC\bin\amd64 is the default x64 compiler on windows.

**Comment by GregDomjan** [comment]
@vindiagram  Perhaps needs an example pom.xml and log output, as have not had this issue.  
The properties that would be set by `vcvarsall` are intended to be set by maven as
 * the environment needs to be different when building both x86 and x64 in the same session
 * the environment is otherwise cleared to have more reproducible builds, unless flagged to keep

**Comment by vindiagram** [comment]
Simple hello world project also presents with the same error:

MSVC 2015 installed

`<build>
        <plugins>
            <plugin>
                <groupId>com.github.maven-nar</groupId>
                <artifactId>nar-maven-plugin</artifactId>
                <version>3.10.1</version>
                <extensions>true</extensions>
                <configuration>
                    <architecture>x86</architecture>
                    <libraries>
                        <library>
                            <type>executable</type>
                        </library>
                    </libraries>
                </configuration>
            </plugin>
        </plugins>
    </build>`
 
 Produced the following error code: -1073741515
 
I just tried running that execution inside of a separate cmd prompt instead of the integrated terminal of intellij.
I got the following pop up error:
The code execution cannot proceed because mspdb140.dll was not found. Reinstalling the program may fix this problem.

This dll does exist within my installation at 2 locations only: 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\mspdb140.dll
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\mspdb140.dll

When executing the same command with "vcvarsall amd64_x86" it compiles succesfully.
The execution of the vcvarsall script adds the following directories to the front of the path:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64

The amd64_x86 directory is first in the path ensuring that its cl.exe is what is called, then followed by the amd64 directory that includes the remaining necessary libraries required to run the executable.

It appears in the case of at least MSVC 2015 that other cross compile directories have dependent libraries in the top level bin or bin\amd64 directories required for execution.    
    
I understand the complications of using the vcvarsall script with the overall design of the nar-maven-plugin. I was not suggesting its use only the error that I had seen and it being alleviated by its use.

**Comment by GregDomjan** [comment]
Think the following outlines the problem, if somebody has time to take it up and raise a PR
 - It seems my previous misunderstanding is based on using an older version.

The path is intended to be adjusted from    `getMsvc().configureCCTask(task);`  which seems to have the configuration that you expect from vcvars.

The `task.addEnv` acts immediately on the attached compiler and linker definitions,  so there could be a problem for the linker and paths.  Initially I thought the `NarCompileMojo.createLibrary`  is attaching the linker definition after the call to configureCCTask,  so the linker doesn't get the udpated environment path.

After some testing of latest version found some log messages `[DEBUG] Setting environment variable:` where missing.
Then found that code had been commented at Revision: 5ca8f0374ccc52cffa403bbc541522c4f36b76fd
"Replace the implementation of  command execution with the standard Java execution and show the command executed"
Has cut out clearing/setting the environment through the introduction of CommandExecution and use of ProcessBuilder
So since nar version 3.7.0

Perhaps workaround try 3.6


`CommandExecution.runCommand` needs to be expanded to work on `boolean newEnvironment, Environment env`  or that change needs to be reverted
